version: "3"
exclude_patterns:
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'public/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/__tests__/'
  - '**/vendor/'
  - '**/*.d.ts'

# Following https://docs.codeclimate.com/docs/advanced-configuration#section-checks
